# Don't touch this file otherwise your device may stop working.
# Use override.yaml to modify required settings.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

override: !include [override.d, override.yaml]

logging: !include logging.yaml

kvmd:
    auth: !include auth.yaml

    hid:
        type: spi
        chip: 0
        bus: 0
        sw_cs_pin: 7
        sw_cs_per_byte: true
        reset_pin: 25
        reset_inverted: true
        reset_self: true
        power_detect_pin: 16
        power_detect_pull_down: true

    atx:
        type: gpio

    msd:
        type: disabled

    streamer:
        h264_bitrate:
            default: 5000
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-video"
            - "--persistent"
            - "--dv-timings"
            - "--format=uyvy"
            - "--encoder=m2m-image"
            - "--workers=3"
            - "--quality={quality}"
            - "--desired-fps={desired_fps}"
            - "--drop-same-frames=30"
            - "--unix={unix}"
            - "--unix-rm"
            - "--unix-mode=0660"
            - "--exit-on-parent-death"
            - "--process-name-prefix={process_name_prefix}"
            - "--notify-parent"
            - "--no-log-colors"
            - "--jpeg-sink=kvmd::ustreamer::jpeg"
            - "--jpeg-sink-mode=0660"
            - "--h264-sink=kvmd::ustreamer::h264"
            - "--h264-sink-mode=0660"
            - "--h264-bitrate={h264_bitrate}"
            - "--h264-gop={h264_gop}"


vnc:
    memsink:
        jpeg:
            sink: "kvmd::ustreamer::jpeg"
        h264:
            sink: "kvmd::ustreamer::h264"
